= Introducere
Spondilodiscita infecțioasă reprezintă o afecțiune serioasă a coloanei vertebrale, caracterizată prin inflamația infecțioasă a discului intervertebral și a corpurilor vertebrale adiacente. Deși relativ rară, incidența sa a înregistrat o creștere în ultimele decenii, în parte datorită îmbunătățirii tehnicilor de diagnostic și a creșterii populației cu factori de risc, precum vârsta înaintată, prezența comorbidităților și stările de imunocompromisie. Această patologie poate avea consecințe devastatoare, incluzând distrucția structurală a coloanei vertebrale, deformări, durere cronică severă și complicații neurologice potențial invalidante, cum ar fi compresia medulară sau radiculară, care necesită adesea intervenție chirurgicală urgentă.
Diagnosticul precoce al spondilodiscitei poate fi dificil, deoarece simptomele inițiale sunt adesea nespecifice și pot mima alte afecțiuni spinale degenerative sau mecanice. Un management optim, care include identificarea rapidă a agentului patogen, inițierea promptă a terapiei antimicrobiene adecvate și o evaluare riguroasă a extinderii leziunilor și a complicațiilor, este crucial pentru a limita progresia bolii și a îmbunătăți prognosticul pacientului.
În acest context, imagistica medicală deține un rol fundamental și indispensabil în întregul proces de management al spondilodiscitei. De la tehnicile inițiale, precum radiografia convențională, până la metodele avansate, de înaltă rezoluție, precum tomografia computerizată (CT) și imagistica prin rezonanță magnetică (IRM), arsenalul imagistic permite vizualizarea modificărilor structurale și inflamatorii la nivel vertebral și paravertebral, identificarea abceselor și a implicării neurale, precum și monitorizarea răspunsului la tratament. IRM-ul, în particular, este considerat standardul de aur datorită sensibilității și specificității sale superioare, mai ales în stadiile incipiente ale bolii și în evaluarea țesuturilor moi.
Cu toate că ghidurile clinice subliniază importanța imagisticii, complexitatea cazurilor clinice întâlnite în practica de zi cu zi, variabilitatea prezentării bolii, multitudinea comorbidităților asociate și spectrul larg al complicațiilor pot influența procesul decizional, inclusiv alegerea modalităților imagistice și a strategiei terapeutice (conservatoare vs. chirurgicală). Înțelegerea modului în care anumiți factori specifici, cum ar fi comorbiditățile pacientului și caracteristicile imagistice identificate, se corelează cu managementul clinic, poate oferi perspective valoroase asupra practicii curente.
Pornind de la aceste premise, scopul principal al prezentei lucrări de disertație este de a evalua contribuția imagisticii medicale în managementul spondilodiscitei infecțioase, analizând o cohortă de pacienți diagnosticați și tratați într-un serviciu de urgență.
Obiectivele specifice ale studiului includ:
+ Descrierea caracteristicilor demografice și clinice ale cohortei de pacienți cu spondilodiscită incluși în studiu.
+ Analiza frecvenței utilizării diferitelor modalități imagistice (Radiografie, CT, IRM, Ecografie, Medicină Nucleară) în evaluarea acestor pacienți.
+ Explorarea impactului numărului de comorbidități asociate asupra numărului de investigații imagistice efectuate per pacient.
+ Evaluarea asocierii dintre prezența anumitor caracteristici imagistice (precum eroziuni, colecții, hernie de disc lombară) și decizia terapeutică (tratament conservator versus chirurgical).
+ Interpretarea constatărilor în context clinic și a literaturii de specialitate, identificând limitările studiului și sugerând direcții de cercetare viitoare.
Lucrarea este structurată în capitole care acoperă revizuirea literaturii privind spondilodiscita (@spondilodiscita ), rolul imagisticii în managementul acesteia (@rolul-imagisticii), metodologia studiului (@metode), prezentarea rezultatelor obținute (@rezultate, interpretarea și discuția acestora (@discuții), studii de caz ilustrative (@cazuri), direcții viitoare de cercetare (@direcții) și concluziile studiului (@concluzii).

