== Etiologie și microbiologie

Un focar infecțios îndepărtat a fost identificat în aproape jumătate din cazurile de spondilodiscită raportate de _Mylona et al_ @PyogenicVertebralOsteomyelitis2009. Autorii au descris aceste focare ca provenind din tractul genito-urinar (17%), piele și țesuturi moi (11%), dispozitive intravasculare (5%), tractul gastrointestinal (5%), tractul respirator (2%) și cavitatea orală (2%). Endocardita infecțioasă a fost raportată în 12% dintre cazuri. Diverse studii au identificat și alți factori predispozanți. Diabetul zaharat este cel mai frecvent factor de risc @EpidemiologyAcuteVertebral1998, însă alți factori includ vârsta înaintată, consumul de droguri injectabile, imunosupresia, malignitatea, insuficiența renală, bolile reumatologice, ciroza hepatică și intervențiile chirurgicale anterioare la nivelul coloanei vertebrale @ComparativeStudyPostoperative2005. 
#linebreak()
Proporția infecțiilor sanguine cu _Staphylococcus aureus_ complicate cu osteomielită vertebrală variază între 1,7% (146 din 8739 de cazuri) și 3% (22 din 724 de cazuri) în două serii ample de studii @IncreasingFrequencyVertebral1997 @ClinicalIdentifiersComplicated2003. Pacienții cu cel mai mare risc (6% dintre infecțiile sanguine cu _S. aureus_) sunt cei cu vârsta de peste 50 de ani, cu infecții dobândite în comunitate și fără un portal evident de intrare al infecției @IncreasingFrequencyVertebral1997. Într-un studiu realizat de _Fowler et al._, riscul de osteomielită vertebrală la pacienții cu bacteriemie asociată cu dispozitive intravasculare a fost de 2,2% (7 din 324 de cazuri) @ClinicalIdentifiersComplicated2003. Rezistența la meticilină a fost raportată tot mai frecvent în ultimele două decenii @HematogenousPyogenicSpinal2000 @HematogenousMethicillinresistantStaphylococcus2007. Deși apariția _Staphylococcus aureus_ rezistent la meticilină (MRSA) dobândit în comunitate, pozitiv pentru leucocidina Panton-Valentine, care provoacă osteomielită la copii, este îngrijorătoare, cazurile care implică coloana vertebrală sunt extrem de rare în prezent @CommunityacquiredMethicillinresistantMethicillinsusceptible2004 @ChangingPatternsAcute2006.
#linebreak()
_Pseudomonas aeruginosa_ este o cauză rară de spondilodiscită. Într-o serie de 61 de pacienți din perioada 1969–1979, majoritatea fiind utilizatori de droguri injectabile, _P. aeruginosa_ a fost patogenul cel mai frecvent izolat, fiind identificat în 48% dintre cazuri @Analysis61Cases1991. Acest rezultat nu a fost confirmat în alte studii, _Staphylococcus aureus_ rămânând principalul agent cauzator la utilizatorii de droguri injectabile @SpinalInfectionIntravenous2007.

#linebreak()

Tuberculoza (TBC) este cea mai frecventă cauză de infecție spinală la nivel mondial @TuberculosisSpineHistorical2007, reprezentând între 9% și 46% din cazuri în țările dezvoltate @ComparativeAnalysisTuberculous2007 @PyogenicTuberculousBrucellar1997. Implicarea sistemului osos apare în 1%–3% din infecțiile cu TB, jumătate dintre acestea afectând coloana vertebrală @TuberculosisSpineHistorical2007. În țările cu incidență scăzută a tuberculozei, aceasta este întâlnită frecvent în grupurile etnice provenind din zone cu endemie ridicată @VertebralOsteomyelitisGoteborg2001. În cel mai mare studiu epidemiologic realizat până în prezent despre spondilodiscită, tuberculoza spinală a fost semnificativ mai frecventă la pacienții sub 40 de ani comparativ cu cei peste 40 de ani (risc relativ 2,7, interval de încredere de 95% între 2,39 și 3,08) @EpidemiologyVertebralOsteomyelitis2007.

