== Epidemiologie

Spondilodiscita reprezintă o inflamație infecțioasă a discului intervertebral și a corpurilor vertebrale adiacente, fiind o afecțiune rară, dar gravă, cu potențial de a provoca distrugeri structurale semnificative și complicații neurologice. Etiologia poate fi variată, incluzând infecții bacteriene piogene, infecții tuberculoase și, mai rar, infecții fungice. În practica clinică, spondilodiscita este deosebit de importantă datorită diagnosticului adesea tardiv, care poate conduce la complicații severe precum instabilitatea coloanei vertebrale, abcesul epidural sau compresiunea măduvei spinării. În plus, infecția poate progresa subacut, ceea ce complică și mai mult diagnosticarea precoce.

Capitolul de epidemiologie își propune să ofere o perspectivă detaliată asupra prevalenței și incidenței spondilodiscitei, identificând totodată factorii de risc asociați și distribuția geografică a bolii. În acest context, vor fi prezentate date epidemiologice actuale care evidențiază diferențele regionale, influența condițiilor socio-economice și evoluția incidenței în ultimele decenii. Scopul este de a sublinia relevanța spondilodiscitei în diferite populații și de a evidenția necesitatea unor strategii eficiente de diagnostic și tratament, având în vedere tendințele epidemiologice emergente.

== Prevalență și incidență

Prevalența spondilodiscitei variază semnificativ la nivel global, fiind influențată de factori precum accesul la servicii medicale, prevalența bolilor cronice (de exemplu, diabetul și bolile autoimune), și starea socio-economică. În țările dezvoltate, prevalența raportată a spondilodiscitei este de aproximativ 0,4 - 2,4 cazuri la 100.000 de persoane pe an, cu o ușoară creștere observată în ultimele decenii datorită îmbunătățirii tehnicilor de diagnosticare și creșterii numărului de pacienți imunocompromiși @RoleNuclearMedicine2012. În regiunile în curs de dezvoltare, prevalența poate fi subraportată din cauza accesului limitat la îngrijirea medicală și a resurselor diagnostice insuficiente @RadionuclideImagingMusculoskeletal2016.

Incidența spondilodiscitei variază între 2,2 și 7,4 cazuri la 100.000 de persoane pe an în țările dezvoltate, cu o incidență mai mare în populațiile vârstnice și la pacienții cu comorbidități preexistente, cum ar fi diabetul sau insuficiența renală cronică @ImagingAssessmentSpine2024. În țările în curs de dezvoltare, incidența poate fi mai mare din cauza prevalenței ridicate a tuberculozei și a altor infecții cronice, dar datele precise sunt adesea limitate. De exemplu, incidența spondilodiscitei tuberculoase rămâne semnificativă în anumite regiuni din Asia și Africa, reprezentând o proporție considerabilă din cazurile globale de spondilodiscită @RadionuclideImagingMusculoskeletal2016.

Incidența și prevalența spondilodiscitei au prezentat o creștere treptată în ultimele decenii, în special în țările dezvoltate. Această creștere este atribuită în parte îmbunătățirii tehnicilor imagistice, cum ar fi IRM-ul și PET/CT, care permit o diagnosticare mai precisă și mai timpurie a afecțiunii. În plus, o proporție mai mare a populației trăiește mai mult timp cu comorbidități care predispun la spondilodiscită, cum ar fi diabetul, bolile autoimune și utilizarea pe termen lung a corticosteroizilor @RoleNuclearMedicine2012 @ImagingAssessmentSpine2024. În același timp, avansul în tratamentele antimicrobiene și în managementul chirurgical al infecțiilor spinale a contribuit la o scădere a mortalității și la îmbunătățirea prognosticului pe termen lung pentru pacienți @RadionuclideImagingMusculoskeletal2016.

== Factori de risc

Vârsta este un factor de risc semnificativ pentru dezvoltarea spondilodiscitei, incidența crescând odată cu înaintarea în vârstă. Majoritatea cazurilor sunt raportate la pacienți cu vârste de peste 50 de ani, cu un vârf în jurul vârstei de 70 de ani. În ceea ce privește sexul, bărbații sunt mai predispuși la spondilodiscită, cu o rată de incidență mai mare comparativ cu femeile. Această diferență este atribuită în parte prevalenței mai mari a factorilor de risc, cum ar fi diabetul și consumul de alcool, în rândul bărbaților @RoleNuclearMedicine2012. Etnia poate juca, de asemenea, un rol, deși datele sunt limitate. Anumite grupuri etnice din regiunile cu prevalență ridicată a tuberculozei, cum ar fi Asia de Sud și Africa subsahariană, prezintă un risc mai mare de SD tuberculoasă @ImagingAssessmentSpine2024.

Comorbiditățile joacă un rol central în dezvoltarea spondilodiscitei. Diabetul zaharat este unul dintre cei mai importanți factori de risc, pacienții diabetici având un risc semnificativ mai mare de a dezvolta această afecțiune din cauza statusului lor imun compromisul. Imunodeficiențele, fie ele congenitale, dobândite (de exemplu, HIV/SIDA) sau iatrogene (de exemplu, tratamente cu corticosteroizi pe termen lung), cresc de asemenea riscul de spondilodiscită. Utilizarea de droguri intravenoase este un alt factor de risc major, legat de introducerea directă a patogenilor în circulația sanguină, ceea ce poate duce la infecții hematogene ale coloanei vertebrale @RadionuclideImagingMusculoskeletal2016  @ImagingAssessmentSpine2024.

Condițiile socio-economice precare sunt strâns legate de o incidență mai mare a spondilodiscitei. Accesul limitat la servicii medicale și diagnostic precoce, igiena precară, nutriția deficitară, și ratele mai mari de infecții cronice, cum ar fi tuberculoza, contribuie la riscul crescut de spondilodiscită în populațiile defavorizate. În țările în curs de dezvoltare, unde accesul la îngrijire medicală este limitat și prevalența tuberculozei este ridicată, spondilodiscita tuberculoasă este mai frecventă. În contrast, în țările dezvoltate, riscul este mai mare la pacienții vârstnici și imunocompromiși din cauza incidenței crescute a bolilor cronice și a utilizării pe termen lung a terapiilor imunosupresive @RoleNuclearMedicine2012.

=== Grupe populaționale vulnerabile

Analiza epidemiologică a spondilodiscitei în populația pediatrică și geriatrică arată o creștere semnificativă a incidenței în rândul vârstnicilor, în special în Germania, unde 59.6% dintre cazuri apar la pacienți cu vârsta de 70 de ani și peste. Staphylococcul și Escherichia coli sunt principalii agenți patogeni implicați. În contrast, la copii, studiile din Coreea de Sud indică faptul că _S. aureus_ și _M. tuberculosis_ sunt cauzele predominante ale spondilodiscitei, ceea ce subliniază diferențele importante în etiologie între cele două grupe de vârstă @EtiologyClinicalPresentation2016 

Prevalența spondilodiscitei este semnificativ mai mare în rândul pacienților imunocompromiși, în special în cei cu HIV/SIDA, cancer, sau cei supuși transplanturilor. Acești pacienți sunt expuși unui risc crescut de a dezvolta infecții severe, inclusiv spondilodiscită, datorită stării lor imunitare compromise. În Iran, seroprevalența toxoplasmozei a fost de 45.9% în rândul pacienților cu HIV/SIDA și 43.6% în pacienții cu cancer, subliniind vulnerabilitatea acestor grupe la infecții opportunistice @EpidemiologySpondylodiscitisGermany2023 